project:
  type: website
  output-dir: docs

website:
  title: "Takeen Shamloo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: 
      light: lux
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

